namespace PolicyManager.Models;

/// <summary>
///     Marks an entity whose provenance and change history are recorded in the database itself.
/// </summary>
/// <remarks>
///     Two separate questions are answered by these properties. <see cref="RowVersion" /> answers
///     "did anyone else change this row while I was working on it?" — the last-writer-wins behaviour
///     of a bare <c>UPDATE</c> means two operators editing the same policy can otherwise silently
///     discard each other's work, and nothing in the logs says so. The remaining properties answer
///     "who did it, and when?", which is the minimum an insurer needs to answer a complaint about a
///     decision; without them the only record is an outbox message that a consumer may never have
///     read.
/// </remarks>
public interface IAuditableEntity
{
    /// <summary>
    ///     When the row was first written, in UTC.
    /// </summary>
    DateTime CreatedAt { get; set; }

    /// <summary>
    ///     Who created the row, or null when the write did not originate from a request.
    /// </summary>
    string? CreatedBy { get; set; }

    /// <summary>
    ///     When the row was last modified, in UTC, or null while it has never been modified.
    /// </summary>
    DateTime? UpdatedAt { get; set; }

    /// <summary>
    ///     Who last modified the row, or null while it has never been modified.
    /// </summary>
    string? UpdatedBy { get; set; }

    /// <summary>
    ///     The row's concurrency token, maintained by the database.
    /// </summary>
    /// <remarks>
    ///     Generated by SQL Server as a monotonically increasing <c>rowversion</c>, so it is neither
    ///     guessable nor forgeable by a client: a caller can only echo back a value the database gave
    ///     it. EF Core appends it to the <c>WHERE</c> clause of every update, and a mismatch means
    ///     someone else's write landed in between.
    /// </remarks>
    byte[] RowVersion { get; set; }
}
